// <auto-generated />
using System;
using MdExplorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MdExplorer.Data.Migrations
{
    [DbContext(typeof(MdExplorerDbContext))]
    [Migration("20260608090000_AddFts5Index")]
    partial class AddFts5Index
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MdExplorer.Core.Models.MarkdownFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AbsolutePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNameWithoutExtension")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IndexedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastWriteTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AbsolutePath")
                        .IsUnique()
                        .HasDatabaseName("IX_MarkdownFiles_AbsolutePath");

                    b.HasIndex("LastWriteTimeUtc")
                        .HasDatabaseName("IX_MarkdownFiles_LastWriteTimeUtc");

                    b.ToTable("MarkdownFiles", (string)null);
                });

            modelBuilder.Entity("MdExplorer.Core.Models.MarkdownDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FrontmatterJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MarkdownFileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutlinksJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("_renderedHtmlGz")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("RenderedHtmlGz");

                    b.HasKey("Id");

                    b.HasIndex("MarkdownFileId")
                        .IsUnique()
                        .HasDatabaseName("IX_MarkdownDocuments_MarkdownFileId");

                    b.ToTable("MarkdownDocuments", (string)null);
                });

            modelBuilder.Entity("MdExplorer.Core.Models.MarkdownFileTag", b =>
                {
                    b.Property<Guid>("MarkdownFileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("MarkdownFileId", "TagId");

                    b.HasIndex("TagId")
                        .HasDatabaseName("IX_MarkdownFileTags_TagId");

                    b.ToTable("MarkdownFileTags", (string)null);
                });

            modelBuilder.Entity("MdExplorer.Core.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Slug");

                    b.ToTable("Tags", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
